application: odenkiapi
version: python-0008
#runtime: python
runtime: python27
api_version: 1

default_expiration: "1d 1h"

threadsafe: no
inbound_services:
- warmup

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /html
  static_dir: html

- url: /css
  static_dir: css

- url: /api/([A-Za-z]+)
  script: api/\1.py
  
- url: /post
  script: post.py

- url: /admin
  script: index.py

- url: /Sender
  script: SenderRequestHandler.py
  
- url: /RawData
  script: RawDataRequestHandler.py

- url: /RawDataNonCached
  script: RawDataRequestHandler.py
  
- url: /RawData2
  script: RawDataRequestHandler.py

- url: /Metadata
  script: MetadataRequestHandler.py
  
- url: /Data
  script: DataRequestHandler.py

- url: /Last
  script: LastRequestHandler.py

- url: /sandbox/hello
  script: sandbox/hello.py

- url: /Equipment
  script: Equipment.py
  
- url: /GoogleDocs
  script: GoogleDocs.py

- url: /google686f6b490a533df7.html
  script: google686f6b490a533df7.py 

- url: /OdenkiUser
  script: OdenkiUser.py
  
- url: /Twitter
  script: Twitter.py
  
- url: /Facebook
  script: Facebook.py
  
- url: /Foursquare
  script: Foursquare.py

- url: /Spreadsheet
  script: Spreadsheet.py

- url: /Command
  script: Command.py
  
- url: /GoogleAuth*
  script: GoogleAuth.py
  
- url: /MyRequestHandler*
  script: MyRequestHandler.py
- url: /
  static_files: html/top.html
  upload: html/top.html

- url: /RawData
  script: RawDataRequestHandler.py

- url: /RawData2Cached
  script: RawDataRequestHandler.py

- url: /OdenkiSession*
  script: OdenkiSession.py
- url: /RawDataNdb
  script: RawDataNdb.py
