application: odenkiapi
version: python-0004
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /post
  script: post.py

- url: /Sender
  script: SenderRequestHandler.py
  
- url: /RawData
  script: RawDataRequestHandler.py
  
- url: /Metadata
  script: MetadataRequestHandler.py
  
- url: /Data
  script: DataRequestHandler.py

- url: /Last
  script: LastRequestHandler.py

- url: /sandbox/hello
  script: sandbox/hello.py

- url: /
  script: index.py
